### ISSUE TITLE
(enhancement) extending django-admin-shortcuts to all app pages in admin

### ISSUE THREAD

**Issue by jaredrunyon** [alesdotio/django-admin-shortcuts#25]
(previous conversation moved here)

It's not possible at the moment, but it would probably be easy to add by changing the admin/base_site.html template to include something like this at the top:

{% load admin_shortcuts_tags %}

{% block breadcrumbs %}
	<div class="admin_shortcuts">
		{% admin_shortcuts %}
	</div>
{% endblock %}

{% block extrastyle %}<style type="text/css">{% admin_shortcuts_css %}</style>
{{ block.super }}
{% endblock %}

{% block extrahead %}{{ block.super }}{% admin_shortcuts_js %}{% endblock %}

Adding the above code to base_site.html will not work because of other templates overriding the breadcrumbs tag.

So, there are two options to make this work:

1. the above code can be implemented in base.html BUT by removing the breadcrumbs tag and adding the actual admin_shortcuts_css tag and admin_shortcuts_js tag to the already existing block_extrastyle and block_extrahead tags appropriately. This is kind of hacky though because alot of other templates i.e. change_form, change_list, and app_index all are using the breadcrumbs tag. This leads to those other templates going to render the breadcrumbs tag but there is none in the parent template.

2. a cleaner approach is to do the above code change NOT in base.html and actually in the templates you wish to override them in i.e. change_form,change_list, and app_index.

**Comment by jaredrunyon** [comment]
Hello, did you happen to play with this yet?

**Comment by alesdotio** [comment]
No, sorry I did not have time yet. Maybe during the coming holidays, but I can't promise anything :(

**Comment by jaredrunyon** [comment]
Ok, no big deal. I did however already implement the above suggestion on my project to make it work. So I now have the shortcuts on every page in the admin. If you don't get around to it or you are maybe interested in a collaboration or an outside contribution to the repo, let me know and ill send a pull request.

**Comment by alesdotio** [comment]
Hey there! It's been a while but I just released 2.0, which includes this change among other things like support for Django 2.0, Python 3 and many more font icons.

To enable it, add:

    ADMIN_SHORTCUTS_SETTINGS = {
        'show_on_all_pages': True,
    }
