### ISSUE TITLE
Django 2

### ISSUE THREAD

**Issue by cyberbudy** [alesdotio/django-admin-shortcuts#31]
Is this plugin compatible with django version 2.0?

**Comment by cyberbudy** [comment]
Ok, I have found feature/2.0. It works pretty well, except that `title` in shortcuts cannot be translatable now.
There is type error `must be str, not __proxy__` here `admin_shortcuts/templatetags/admin_shortcuts_tags.py in admin_shortcuts, line 61`

I suppouse it's because proxy objects can't be concatenated directly.

`shortcut['icon'] = get_shortcut_class(shortcut.get('url_name', shortcut.get('url', ''))+shortcut.get('title', ''))`

**Comment by alesdotio** [comment]
Nice catch! Using `force_text` around it should solve it. Will look into it.

**Comment by alesdotio** [comment]
I just released 2.0.0 which fixes this exception 👍
